Fix update process

diff --git a/updateHAB b/updateHAB
--- a/updateHAB
+++ b/updateHAB
@@ -2,11 +2,9 @@
 
 # The location for downloads
 DOWN_DIR="/opt/DOWN"
-#DOWN_DIR="/home/mark/test/DOWN"
 
 # The location of the openHAB installation
-OH2_DIR="/opt/openhab"
-#OH2_DIR="/home/mark/test/openhab"
+OH2_DIR="/opt/openhab2"
 
 # Location of Karaf runtime
 KARAFBIN_DIR="${OH2_DIR}/runtime/bin"
@@ -19,7 +17,6 @@ HABPANEL_CONFIG="${OH2_DIR}/userdata/config/org/openhab/habpanel.config"
 
 # The location of SmartHome Designer
 SMD_DIR="/opt/ohdesign"
-#SMD_DIR="/home/mark/test/ohdesign"
 
 # Name of OH2 snapshot file. Update this if this name changes.
 OH2_FILE="openhab-2.1.0-SNAPSHOT.zip"
@@ -56,7 +53,7 @@ while true ; do
 		echo "Usage: $0 [--skip-designer]"
 		exit 0 
 		;;
-	--skip-designer)
+	--get-designer)
 		dflag=1
 		shift
 		;;
@@ -107,15 +104,14 @@ if [ -f ${HABPANEL_CONFIG} ]; then
 fi
 
 # These files and directories need to be deleted
-echo "Deleting old directories and files"
+echo "Deleting old directories"
 cd ${OH2_DIR}
 rm -rf ${OH2_DIR}/runtime
 rm -rf ${OH2_DIR}/userdata/cache
 rm -rf ${OH2_DIR}/userdata/tmp
-# Deletes org.apache.karaf.*.*, excluding org.apache.karaf.shell.cfg
-find ${KARAFETC_DIR} -name "org.apache.karaf.*.*" ! -name "org.apache.karaf.shell.cfg" -type f -exec rm -f {} +
-# Deletes *.properties
-find ${KARAFETC_DIR} -name "*.properties" -type f -exec rm -f {} +
+
+# Deletes userdata/etc/* with the excption of org.ops4j.pax.logging.cfg and org.apache.karaf.shell.cfg
+find ${KARAFETC_DIR} -type f \( -name "*" ! -name  "org.ops4j.pax.logging.cfg" ! -name "org.apache.karaf.shell.cfg" \) -exec rm -f {} +
 
 # Lay down the files from the new version (not overwriting files that exist)
 echo "Unzipping openHAB"
@@ -125,12 +121,12 @@ unzip -n -q ${DOWN_DIR}/${OH2_FILE}
 rm -f ${OH2_DIR}/*.bat
 
 # If we downloaded the designer, unzip it
-if [ -z ${dflag} ]; then
-	echo "Unzipping designer"
-	cd ${SMD_DIR}
-	rm -rf ${SMD_DIR}/p2/* ${SMD_DIR}/plugins 
-	unzip -q -o ${DOWN_DIR}/${SMD_FILE}
-fi
+#if [ -z ${dflag} ]; then
+#	echo "Unzipping designer"
+#	cd ${SMD_DIR}
+#	rm -rf ${SMD_DIR}/p2/* ${SMD_DIR}/plugins 
+#	unzip -q -o ${DOWN_DIR}/${SMD_FILE}
+#fi
 
 # Start with empty log files
 if [ -d "${OH2_DIR}/userdata/logs" ]; then
@@ -145,26 +141,27 @@ if [ -d "${OH2_DIR}/userdata/logs" ]; then
 	cp /dev/null ${OH2_DIR}/userdata/logs/zwave.log
 fi
 
-SERVICE_DIR=${DOWN_DIR}/service
+#SERVICE_DIR=${DOWN_DIR}/service
 
-if [ ! -d ${SERVICE_DIR} ]; then
-	echo "Error: The directory and files are not there: " ${SERVICE_DIR}
-	exit 1
-fi
+#if [ ! -d ${SERVICE_DIR} ]; then
+#	echo "Error: The directory and files are not there: " ${SERVICE_DIR}
+#	exit 1
+#fi
 
-echo "Enabling openHAB as a service..."
+#echo "Enabling openHAB as a service..."
 
-if [ ! -d ${KARAFLIB_DIR}/wrapper ]; then
-	mkdir --parents ${KARAFLIB_DIR}/wrapper
-fi
+#if [ ! -d ${KARAFLIB_DIR}/wrapper ]; then
+#	mkdir --parents ${KARAFLIB_DIR}/wrapper
+#fi
 
-cp -n ${SERVICE_DIR}/openHAB-wrapper        ${KARAFBIN_DIR}
-cp -n ${SERVICE_DIR}/openHAB-service        ${KARAFBIN_DIR}
-cp -n ${SERVICE_DIR}/openHAB.service        ${KARAFBIN_DIR}
-cp -n ${SERVICE_DIR}/libwrapper.so          ${KARAFLIB_DIR}/wrapper/
-cp -n ${SERVICE_DIR}/karaf-wrapper.jar      ${KARAFLIB_DIR}/wrapper/
-cp -n ${SERVICE_DIR}/karaf-wrapper-main.jar ${KARAFLIB_DIR}/wrapper/
+#cp -n ${SERVICE_DIR}/openHAB-wrapper        ${KARAFBIN_DIR}
+#cp -n ${SERVICE_DIR}/openHAB-service        ${KARAFBIN_DIR}
+#cp -n ${SERVICE_DIR}/openHAB.service        ${KARAFBIN_DIR}
+#cp -n ${SERVICE_DIR}/libwrapper.so          ${KARAFLIB_DIR}/wrapper/
+#cp -n ${SERVICE_DIR}/karaf-wrapper.jar      ${KARAFLIB_DIR}/wrapper/
+#cp -n ${SERVICE_DIR}/karaf-wrapper-main.jar ${KARAFLIB_DIR}/wrapper/
 #cp -n ${SERVICE_DIR}/openHAB-wrapper.conf   ${KARAFETC_DIR}/
 
-systemctl enable ${KARAFBIN_DIR}/openHAB.service
+#systemctl enable ${KARAFBIN_DIR}/openHAB.service
+systemctl daemon-reload
 
